apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: core
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: .env-int
          env:
            - name: ENV
              value: "intergration"

