apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -prod

patches:
  - path: patches/deployment.yaml

images:
  - name: ghcr.io/lootopia-org/core
    newTag: main

